### ISSUE TITLE
Bug?: "return 7" kommt als "8" an

### ISSUE THREAD

**Issue by Scriptim** [ac1235/core#3]
Bei meiner AI ist des Öfteren der Fehler aufgetreten, dass `Player 1 moved to 1,8` ausgegeben wird.
Durch Debugging hab ich herausgefunden, dass dies immer passiert, wenn als Koordinate `7` zurückgegeben wird.

Auch als ich die Datei auf

    def turn(board, symbol)
        return 0, 7
reduziert habe, ist der Fehler weiter aufgetreten.

Ich bin erst davon ausgegangen, dass ich versehentlich eine Datei des Spiels verändert habe. Also habe ich das Repo komplett neu geklont und mit der obigen minimierten Datei wieder gegen `crazy.py` gespielt und der Fehler ist weiterhin aufgetreten.

Ist der Bug schon bekannt? Ich hoffe auf einen baldigen Fix oder Hilfe beim Lösen des Problems.

**Comment by Scriptim** [comment]
Gut, ich hab jetzt rausgefunden, woran es liegt. Das scheint offenbar so gewollt zu sein, dass im Browser `1,8` statt `0,7` angezeigt wird, was sehr verwirrend ist. Ich denke, man sollte auch das angezeigt bekommen, was zurückgegeben wird, dann treten solche Fehler/Missverständnisse auch nicht auf... Die Indizes sollten wie auch in Python von 0-7 statt von 1-8 gehen. Bestenfalls könnte man noch eine Beschriftung am Rand der Tabelle für jede Spalte und Zeile hinzufügen um solche Probleme komplett auszuschließen.

**Comment by ac1235** [comment]
Ja, denke daran dass die HTML ansicht für die zuschauer und nicht für die entwickler ist.

**Comment by Scriptim** [comment]
@ac1235 Und wie sollen die Entwickler dann die Spielzüge und Ergebnisse nachvollziehen? Wie gesagt, ich denke zumindest eine Beschriftung des Spielfelds wäre angebracht, um solche Missverständnisse auszuschließen.

**Comment by TheRealMephisto** [comment]
@Scriptim Als Entwickler merkt man sich einfach, dass z.B. eine "0" im Code einer "1" in der HTML Ansicht entspricht, genauso für die anderen Ziffern :D
Eine Beschriftung des Spielfeldes befinde ich jedoch auch für gut!

**Comment by Scriptim** [comment]
@TheRealMephisto Das kann man sich aber auch erst merken, wenn man es weiß. Und vermerkt ist es ja offensichtlich nirgendwo. Da muss man als Entwickler von selbst draufkommen. Da sollte evtl. noch ein Vermerk in der README oder mindestens im Handbook her. Wenn man das nämlich nicht weiß, kann das zu großen Missverständnissen und langem Rätselraten führen (das kann ich so empirisch beurteilen).
