### ISSUE TITLE
src/statistics.py Umgang mit Fehlern

### ISSUE THREAD

**Issue by simonherbert** [ac1235/core#6]
Wenn man src/statistics.py benutzt, und eine der AI's nicht korrekt spielt, z.B. auf ein falsches Feld setzt, wird dies als Sieg für den Gegner gewertet, während dies mit src/CoRe.py zum Abbruch führt ("Player X loses because of wrong gameplay.").

**Comment by TheRealMephisto** [comment]
Ist das nicht dasselbe?

**Comment by simonherbert** [comment]
Hmm, das stimmt. Aber in statistics wird dies nicht als Fehler angezeigt.

Bin hierdrauf aufmerksam geworden, weil ich meine AI auf genau diesen Fehler testen wollte (der extrem selten auftritt), ohne den Command 1000x ausführen zu müssen.
